# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Front_Formulaire.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Custom_Widgets.Widgets import *
# from Loading_page import SplashScreen
from Requettes import connexion
import time


class Ui_Authentification(object):
    def setupUi(self, Authentification):
        Authentification.setObjectName("Authentification")
        Authentification.resize(408, 480)
        self.centralwidget = QtWidgets.QWidget(Authentification)
        self.centralwidget.setStyleSheet("background-color: rgb(56, 58, 89);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 331, 431))
        self.label.setStyleSheet("border-radius: 20px;\n"
"background-color:rgba(0, 0, 0, 100);\n"
"color:rgba(255, 255, 255, 210);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 70, 151, 61))
        self.label_2.setStyleSheet("background-color: transparent;\n"
"font-size: 50px;\n"
"color:rgba(255, 255, 255, 210);")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(72, 180, 261, 41))
        self.lineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 250, 261, 41))
        self.lineEdit_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.connectBtn = QtWidgets.QPushButton(self.centralwidget)
        self.connectBtn.setGeometry(QtCore.QRect(70, 330, 261, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.connectBtn.setFont(font)
        self.connectBtn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0201005, y1:0.54, x2:0.974874, y2:0.534, stop:0 rgba(255, 85, 255, 255), stop:0.959799 rgba(170, 85, 255, 255));\n"
"color:rgba(255, 255, 255, 210);\n"
"border-color: none;\n"
"border-radius: 10px;")
        self.connectBtn.setObjectName("connectBtn")
        self.charge_formulaire = QtWidgets.QProgressBar(self.centralwidget)
        self.charge_formulaire.setGeometry(QtCore.QRect(120, 440, 161, 23))
        self.charge_formulaire.setStyleSheet("QProgressBar{\n"
"    \n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.0201005, y1:0.54, x2:0.974874, y2:0.534, stop:0 rgba(255, 85, 255, 255), stop:0.959799 rgba(170, 85, 255, 255));\n"
"\n"
"}")
        self.charge_formulaire.setProperty("value", 0)
        self.charge_formulaire.setObjectName("charge_formulaire")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 400, 191, 21))
        self.label_5.setStyleSheet("color:rgba(255, 255, 255, 140);\n"
"background-color: none;")
        self.label_5.setObjectName("label_5")
        self.usernameerror = QtWidgets.QLabel(self.centralwidget)
        self.usernameerror.setGeometry(QtCore.QRect(130, 230, 141, 16))
        self.usernameerror.setStyleSheet("background-color: none;\n"
"color: red;")
        self.usernameerror.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameerror.setObjectName("usernameerror")
        self.passworderror = QtWidgets.QLabel(self.centralwidget)
        self.passworderror.setGeometry(QtCore.QRect(130, 300, 141, 16))
        self.passworderror.setStyleSheet("background-color: none;\n"
"color: red;")
        self.passworderror.setAlignment(QtCore.Qt.AlignCenter)
        self.passworderror.setObjectName("passworderror")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 380, 191, 21))
        self.label_6.setStyleSheet("color:rgba(255, 255, 255, 140);\n"
"background-color: none;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        Authentification.setCentralWidget(self.centralwidget)

        self.retranslateUi(Authentification)
        QtCore.QMetaObject.connectSlotsByName(Authentification)

    def retranslateUi(self, Authentification):
        _translate = QtCore.QCoreApplication.translate
        Authentification.setWindowTitle(_translate("Authentification", "MainWindow"))
        self.label_2.setText(_translate("Authentification", "Log In"))
        self.lineEdit.setPlaceholderText(_translate("Authentification", "User Name"))
        self.lineEdit_2.setPlaceholderText(_translate("Authentification", "PassWord"))
        self.connectBtn.setText(_translate("Authentification", "L o g  I n"))
        self.label_5.setText(_translate("Authentification", "Forgot your User Name or Password? "))
        self.usernameerror.setText(_translate("Authentification", ""))
        self.passworderror.setText(_translate("Authentification", ""))
        self.label_6.setText(_translate("Authentification", ""))

class formulaire(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Authentification()
        self.ui.setupUi(self)
        self.setWindowFlag(Qt.FramelessWindowHint)
        self.setAttribute(Qt.WA_TranslucentBackground)
        self.show()

        self.ui.connectBtn.clicked.connect(self.sessionstart)
        self.datos = connexion.connectToMysql()

    def sessionstart(self):
        self.ui.usernameerror.setText('')
        self.ui.passworderror.setText('')
        users_entry = self.ui.lineEdit.text()
        password = self.ui.lineEdit_2.text()

        users_entry = str("'" + users_entry + "'")
        password = str("'" + password + "'")

        dato1 = self.datos.connectUser(users_entry)
        dato2 = self.datos.connectUser2(password)

        fila1 = dato1
        fila2 = dato2

        if fila1 == fila2:
            if dato1 == [] and dato2 ==[]:
                self.ui.usernameerror.setText('Mauvais Nom')
                self.ui.passworderror.setText('Mauvai mot de passe')
            else:
                if dato1 == []:
                        self.ui.usernameerror.setText('Mauvais nom')
                else:
                        dato1 = dato1[0][1]
                if dato2 == []:
                        self.ui.passworderror.setText('Mauvais mot de passe')
                else: 
                        dato2 = dato2[0][2]

                if dato1 != [] and dato2 != []:
                        for i in range(0,99):
                                time.sleep(0.02)
                                self.ui.charge_formulaire.setValue(i)
                                self.ui.label_6.setText("Chargement...")
                        self.hide()
                        # self.main = SplashScreen()
                        self.close()
                        # self.main.show()
        else:
              self.ui.usernameerror.setText(' Error ')
              self.ui.passworderror.setText(' Error ')
             

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = formulaire()
    sys.exit(app.exec_())
        