# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Loading_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Custom_Widgets.Widgets import *
from main import MiApp



class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(676, 398)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.DropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.DropShadowFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(56, 58, 89);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px\n"
"}")
        self.DropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DropShadowFrame.setObjectName("DropShadowFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.DropShadowFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Headercontainer = QtWidgets.QWidget(self.DropShadowFrame)
        self.Headercontainer.setObjectName("Headercontainer")
        self.WindowBtn = QtWidgets.QWidget(self.Headercontainer)
        self.WindowBtn.setGeometry(QtCore.QRect(560, -10, 80, 42))
        self.WindowBtn.setObjectName("WindowBtn")
        self.gridLayout = QtWidgets.QGridLayout(self.WindowBtn)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.WindowBtn)
        self.pushButton_2.setStyleSheet("background-color: transparent;\n"
"color: rgb(98, 114, 164);\n"
"")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.WindowBtn)
        self.pushButton.setStyleSheet("background-color: transparent;")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.Headercontainer, 0, QtCore.Qt.AlignTop)
        self.TitleLabel = QtWidgets.QLabel(self.DropShadowFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setStyleSheet("color: rgb(254, 121, 199);")
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.DescriptionLabel = QtWidgets.QLabel(self.DropShadowFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.DescriptionLabel.setFont(font)
        self.DescriptionLabel.setStyleSheet("color: rgb(98, 114, 164);")
        self.DescriptionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DescriptionLabel.setObjectName("DescriptionLabel")
        self.verticalLayout.addWidget(self.DescriptionLabel)
        self.progressBar = QtWidgets.QProgressBar(self.DropShadowFrame)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    \n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.0201005, y1:0.54, x2:0.974874, y2:0.534, stop:0 rgba(255, 85, 255, 255), stop:0.959799 rgba(170, 85, 255, 255));\n"
"\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.LoadLabel = QtWidgets.QLabel(self.DropShadowFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(6)
        self.LoadLabel.setFont(font)
        self.LoadLabel.setStyleSheet("color: rgb(98, 114, 164);")
        self.LoadLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LoadLabel.setObjectName("LoadLabel")
        self.verticalLayout.addWidget(self.LoadLabel)
        self.CreditLabel = QtWidgets.QLabel(self.DropShadowFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.CreditLabel.setFont(font)
        self.CreditLabel.setStyleSheet("color: rgb(98, 114, 164);")
        self.CreditLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.CreditLabel.setObjectName("CreditLabel")
        self.verticalLayout.addWidget(self.CreditLabel)
        self.horizontalLayout_2.addWidget(self.DropShadowFrame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.TitleLabel.setText(_translate("SplashScreen", "<strong>chargement...</strong"))
        self.DescriptionLabel.setText(_translate("SplashScreen", "<strong>personnel d\'accueil</strong"))
        self.LoadLabel.setText(_translate("SplashScreen", "chargement..."))
        self.CreditLabel.setText(_translate("SplashScreen", "By universal Book-Africa"))
import  ressource_rc

counter = 0 

class SplashScreen(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_SplashScreen()
        self.ui.setupUi(self)
        self.setWindowFlag(Qt.FramelessWindowHint)
        self.setAttribute(Qt.WA_TranslucentBackground)
        self.show()

        self.shadow = QGraphicsDropShadowEffect(self)
        self.shadow.setBlurRadius(20)
        self.shadow.setXOffset(0)
        self.shadow.setYOffset(0)
        self.ui.DropShadowFrame.setGraphicsEffect(self.shadow)

        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.progress)
        self.timer.start(35)
        
    def progress(self):
        global counter
        self.ui.progressBar.setValue(counter)

        if counter > 100:
            self.timer.stop()
            self.main = MiApp()
            self.close()
            self.main.show()

        counter += 1

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = SplashScreen()
    sys.exit(app.exec_())

    
